### ISSUE TITLE
Hard dependency to NSubstitute 1.7.0.0

### ISSUE THREAD

**Issue by Dakkith** [MRCollective/AutofacContrib.NSubstitute#13]
I've pulled the latest AutofacContrib.NSubstitute package (version (3.2.0)) down through NuGet. I've also got the latest NSubstitute package installed (1.7.1.0).

I'm unable to use AutoSubstitute class since it throws this exception when I attempt to register a substitution:

{"Could not load file or assembly 'NSubstitute, Version=1.7.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"NSubstitute, Version=1.7.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca"}

A workaround is to force a downgrade to NSubstitute 1.7.0.0.

**Comment by BrainCrumbz** [comment]
Hi @MattDavies 

we are experiencing the same problem, but BindingRedirect does not seem to fix that.

AutofacContrib.NSubstitute is 3.3.2.0
NSubstitute is 1.8.2.0
NSpec is 0.9.68.0

Classlibrary Test project has .NET 4.5 target framework, and it has the following `app.config`, created through package manager console (i.e. not manually):

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NSubstitute" publicKeyToken="92dd2e9066daa5ca" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.8.2.0" newVersion="1.8.2.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

In order to run nspec-based tests, we use Visual Studio test runner with the help of this extension:

[NSpec Test Adapter for Visual Studio](https://visualstudiogallery.msdn.microsoft.com/7a52473f-9e1a-40f3-8bd8-6c00ab163609) v0.3.0.

Test explorer reports the following message for failed tests, which is the same (in italian) as this current issue:

> Result Message:	Context Failure: An exception was thrown while executing a resolve operation. See the InnerException for details. ---> Impossibile caricare il file o l'assembly 'NSubstitute, Version=1.7.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca' o una delle relative dipendenze. La definizione di manifesto dell'assembly specificato non corrisponde al riferimento all'assembly. (Eccezione da HRESULT: 0x80131040) (See inner exception for details.)

We have another Classlibrary test project which does not depend on NSubstitute (it still runs on Moq, we're trying to switch to NSubstitute). Actually, there's no other project depending on NSubstitute.

We also tried restarting Visual Studio and killing leftover processes (like debug host process or similar), just in case it was a problem of assembly cached in test runner AppDomain.

Do you have any suggestion?

**Comment by MattDavies** [comment]
Given everything you've said the only possibility I can think of at the moment is that the app.config with your binding redirect isn't getting copied to the right place/name.

Can you see a testclasslibrary.dll.config in the test library's bin folder on running the failing test?

Can you try the call in a regular nunit test just to rule out the test runner not using the right app config artefact?

**Comment by robdmoore** [comment]
Can you run fuslogvw.exe and paste in what it says?

Also, what does this translate to: "Impossibile caricare il file o
l'assembly"

**Comment by BrainCrumbz** [comment]
thanks for your replies.
@MattDavies yes, within test library bin folder I can see the DLL and its related PDB and config files. The config file has the same content as the app.config in VS project.
In order to try a regular NUnit test, should I do that in a separate classlibrary test project, or they can live together in the same assembly with nspec tests?

@robdmoore That quoted output I posted is the italian equivalent of the error message we see in the first post of this thread ("Could not load file or assembly...").
I ran fuslogvw with 'log all binds to disk' already set.

* I could find an item for NSubstitute, Version=1.8.2.0 correctly loaded by *AppName* vstest.executionengine.x86.exe, with *Calling Assembly* unknown.
* I could find an item for Autofac.resources, Version=3.0.0.0 with **a problem** loading the assembly. Here below follows an automatic translation of fusion log (from italian)
* I could not find any other item related to Autofac nor AutofacContrib

The operation failed.
Result association: hr = 0x80070002. Can not find the file specified.

Manager assemblies loaded from: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running with executable C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe
--- Following detailed log of errors.

=== === Status information preassociazione
REG: DisplayName = Autofac.resources, Version = 3.0.0.0, Culture = en, PublicKeyToken = 17863af14b0044da
 (Fully-specified)
REG: AppBase = file:///D:/{{ ## project root path omitted ## }}
REG: privatePath initial = packages\nspec.0.9.68\tools;UnitTest.Business\packages\nspec.0.9.68\tools;Test\UnitTest.Business\bin\Debug
REG: basic dynamic = NULL
REG: basic cache = NULL
REG: AppName = vstest.executionengine.x86.exe
Assembly calling: (Unknown).

REG: the association has its origin in the context of loading default.
REG: use the application configuration file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe.Config
REG: Use the host configuration file:
REG: use the computer configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
REG: reference post-criteria: Autofac.resources, Version = 3.0.0.0, Culture = en, PublicKeyToken = 17863af14b0044da
REG: the same relationship was seen previously. Error hr = 0x80070002.
ERR: fatal error occurs during the pre-download (hr = 0x80070002).

**Comment by MattDavies** [comment]
Use the same project for adding a nunit test. I'm curious as to whether or not it's the nspec runner not reading the binding redirect correctly. If a test in the same test assembly works with a regular nunit runner, we know the assembly is fine and the runner is at fault.

This line here tells me that's what's happening - it should be pointing to the config file for your test assembly: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe.Config

If that's not it I'm not sure - @robdmoore might be able to dig into that output better than I can.

**Comment by BrainCrumbz** [comment]
Here's the followup:

1. Ensure that NSubstitute package is at version 1.8.2
1. Added *NUnit VS Test Adapter* from *Extensions and Updates* (I didn't need that until now)
1. Created simple NUnit test fixture in a separate file, in the same class library project (I've copied the `Example_test_with_standard_resolve()` case with its dummy components)
1. Ran VS test runner against all tests (both NSpec and NUnit)

Outcome: all NSpec tests fails with the previous exception, while NUnit test passes.
If I revert installed NSubstitute to version 1.7.0, all tests pass.

So can you confirm it should be the test runner's fault? In case, I'd try to contact its developers.

**Comment by robdmoore** [comment]
It's kind of sounding like the test runner is not using the app.config file and hence losing the binding redirects.

I'd suggest raising it with nspec to see if they can confirm that is expected behaviour.

Another option is to send us a PR upgrading the version of NSubstitute (including bumping the dependency version in the .nuspec file) and we can push out a new version (meaning you don't need the binding redirect).

**Comment by BrainCrumbz** [comment]
where's this *.nuspec* file located?
