### ISSUE TITLE
Not compatible with Autofac 5.0.0

### ISSUE THREAD

**Issue by jameswrightrg** [MRCollective/AutofacContrib.NSubstitute#38]
[As of 27 January, Autofac 5.0.0 is the latest version.](https://github.com/autofac/Autofac/releases/tag/v5.0.0) Among the breaking changes is the fact that "Containers are Immutable". This is a major breaking change for this repository, where `AutoSubstitute` registers services after the container is built.

I've tried to fix it myself but don't know enough about Autofac or this repository to know what the right solution is. I suspect it will involve a significant breaking change for consumers of this library.

**Comment by robdmoore** [comment]
Hi @jameswrightrg.

Had a quick look. I suspect what you can do is in all of the methods in https://github.com/MRCollective/AutofacContrib.NSubstitute/blob/master/AutofacContrib.NSubstitute/AutoSubstitute.cs that modify the container you can simply create a new container based on combining the registrations in the existing container, with a new registration and then changing the private `Container` property to hold the new container instance.

**Comment by nzbart** [comment]
I have to admit I was a little surprised when I discovered problems with version 5 of NSubstitute not being compatible with version 5 of Autofac, but now I realise that the fact they have the same major version number is simply a unfortunate coincidence.

**Comment by dennisjlee** [comment]
I found a way to adapt the code to work with Autofac 5.0+, but as @jameswrightrg suggested, it would be a major shift in the way that consumers would have to use this library. I wanted to get feedback here before I attempt to send a pull request or anything, since the change would be so incompatible with previous versions.

Major changes:
* AutoSubstitute would be renamed to AutoSubstituteContainerBuilder
* AutoSubstituteContainerBuilder would hold a `ContainerBuilder` instead of an `IContainer`.
* All methods on AutoSubstitute that previously returned an object resolved out of the container would now return void instead (because you can't resolve an object from the container before the container is built). 
* AutoSubstitute.Resolve would be removed completely
* New method `public IContainer Build()` that would just give you back the IContainer that is built. From then on, callers would just use the IContainer to resolve objects (and they'd be responsible for disposing the IContainer when they're done with their test).

Any high-level thoughts on that?

**Comment by twsouthwick** [comment]
I didn't see this thread, and adapted it similarly to @dennisjlee. I've submitted PR #39 to address this. An example change of usage is as follows:

```csharp
using(var autosub = new AutoSubstitute())
{
    var mockA = autosub.Provide<IServiceItem, ServiceItemA>();
    var mockB = autosub.Provide<IServiceItem, ServiceItemB>();
    var component = autosub.Resolve<TestICollectionComponent>();

    Assert.That(component.ServiceItems, Is.Not.Empty);
    Assert.That(component.ServiceItems.Contains(mockA), Is.True);
    Assert.That(component.ServiceItems.Contains(mockB), Is.True);
}
```

is rewritten to:

```csharp
using var autosub = AutoSubstitute.Create()
    .Provide<IServiceItem, ServiceItemA>(out var mockA)
    .Provide<IServiceItem, ServiceItemB>(out var mockB)
    .Build();

var component = autosub.Resolve<TestICollectionComponent>();

Assert.That(component.ServiceItems, Is.Not.Empty);
Assert.That(component.ServiceItems.Contains(mockA.Value), Is.True);
Assert.That(component.ServiceItems.Contains(mockB.Value), Is.True);
```

**Comment by robdmoore** [comment]
v6 is now released, which should resolve this. Big thanks to @twsouthwick  and @mtrtm.
