### ISSUE TITLE
The xmldoc summary for `ResolveAndSubstituteFor` is incorrect

### ISSUE THREAD

**Issue by robdmoore** [MRCollective/AutofacContrib.NSubstitute#9]
It suggests it will return a substitute.

Also, the name of that method sucks, it should be ResolveAndProvide maybe?

**Comment by twsouthwick** [comment]
Is this still needed? I propose this method be obsoleted and a new method be provided that just provides (since we don't necessarily resolve at this moment due to immutability of the container):

```csharp
public class AutoSubstituteBuilder
{
  + public AutoSubstituteBuilder Provide<TService, TImplementation>(params Parameter[] parameters);
  + public AutoSubstituteBuilder Provide<TService>(params Parameter[] parameters);
  + public AutoSubstituteBuilder Provide<TService>(out IProvidedValue<TService> providedValue, params Parameter[] parameters);
}
```

Then it follows the patterns of the `Provide<TService, TImplementation>(...)` that already exists (this also proposes adding a Provide method with no out param so discards aren't needed).
